spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 723870635094-n7marjta2iqi3aild871lv9hm2lkfisp.apps.googleusercontent.com
            client-secret: 0MhkSupCkcYXv0-o5JTw0_x3
            scope: email,profile

app:
  auth:
    tokenSecret: secret1
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/redirect